basePath: /
definitions:
  expense.CreateDto:
    properties:
      amount:
        type: number
      category:
        type: string
      note:
        type: string
      spent_on:
        type: string
    type: object
  expense.PatchDto:
    properties:
      amount:
        type: number
      category:
        type: string
      id:
        type: string
      note:
        type: string
    type: object
  expense.ResponseDto:
    properties:
      amount:
        type: number
      category:
        type: string
      created_on:
        type: string
      id:
        type: string
      note:
        type: string
      spent_on:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API for managing expenses.
  title: BankApi
  version: "1.0"
paths:
  /expenses:
    get:
      description: Returns all expenses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/expense.ResponseDto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List expenses
      tags:
      - expenses
    post:
      consumes:
      - application/json
      description: Creates a new expense
      parameters:
      - description: Expense
        in: body
        name: expense
        required: true
        schema:
          $ref: '#/definitions/expense.CreateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create an expense
      tags:
      - expenses
  /expenses/{id}:
    delete:
      description: Deletes an expense by ID
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/expense.ResponseDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deletes expense
      tags:
      - expenses
    get:
      description: Returns expense by ID
      parameters:
      - description: Expense ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/expense.ResponseDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get an expense by ID
      tags:
      - expenses
    patch:
      consumes:
      - application/json
      description: Updates an expense by ID. Only amount, category, and note can be
        changed.
      parameters:
      - description: Fields to update
        in: body
        name: expense
        required: true
        schema:
          $ref: '#/definitions/expense.PatchDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/expense.ResponseDto'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Updates expense (amount, category, or note)
      tags:
      - expenses
  /expenses/summary:
    get:
      description: Gets a total amount for a category
      parameters:
      - description: Expense category
        in: query
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: number
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Gets expenses summary
      tags:
      - expenses
swagger: "2.0"
